config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  
  resources :users do
    resource :profile
  end
  resources :contacts
  
  get '/about' => 'pages#about'
  root 'pages#home'
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
    
    
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body=params[:contact][:comments]
            
            ContactMailer.contact_email(name,email,body).deliver
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            flash[:danger] = "Error Occured.Message has not been sent"
            redirect_to new_contact_path
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email,:comments)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
		@pro_plan = Plan.find(2)
    end
    
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    
    before_filter :select_plan, only: :new
    
      def create
      super do |resource|
        if params[:plan]
          resource.plan_id = params[:plan]
          if resource.plan_id == 2
            resource.save_with_payment
          else
            resource.save
          end
        end
     end
  end
   
   private
  def select_plan
    unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
   
end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
     <div class = "well">
        <%= form_for @contact do |f| %>
           <div class ="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class:"form-control" %>
            <div>
                
            <div class ="form-group"> 
                <%= f.label :email %>
                <%= f.email_field :email, class:"form-control" %>
            </div>
            
            <div class ="form-group"> 
                <%= f.label :comment %>
                <%= f.text_area :comments,class:"form-control" %>
             </div>
                <%= f.submit 'Submit', class: "btn btn-default" %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dev Match</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-users"></i>
        Dev Match
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right">
        <% if current_user %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h2> About </h2>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
    <h1> Welcome to Dev Match </h1>
    <h3>A membership site where entrpreneurs can meet developers</h3>
</div>

    <div class="row">
       <div class = "col-md-6 text-center">
           <div class="well">
                 <h2> Basic Membership </h2>
                 <h4>Sign up for basic access to the community</h4>
                 <%= link_to "Become A Basic Member", new_user_registration_path(plan: @basic_plan.id), class:"btn btn-primary btn-lg btn-block"%>
           </div>
       </div> 

       <div class="col-md-6 text-center">
           <div class="well">
              <h2> Pro Membership</h2>
              <h4> Sign up for $5/month to access community & contact info!</h4>
              <%= link_to "Become A Pro Member", new_user_registration_path(plan: @pro_plan.id), class:"btn btn-success btn-lg btn-block"%>
           </div>
       </div> 
    </div>